#Basler Camera Settings
camera:
  model: "Basler acA4112-30um"
  serial_number: "12345678"
  
parameters:
  auto_exposure: false
  exposure: 10000 # in microseconds
  auto_gain: true
  gain: 5         # in dB
  pixel_format: "BGR8" 
  image_width: 4096
  image_height: 3000

vicon:
  object1: 'soho'
  object2: 'basler_cam'
  ip_address: "192.168.0.62"
paths:
  vicon_path: 'vicon_data'
  image_path: 'offset_images'